# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45776d66a1a3c4bd176244a715a69d4f09043dd7a006f0c1a4e3f3f4dc981deb122ee76f7b88ca6639be11492c92871529a3de52fceacf222dd906e06745f75e

test:
  secret_key_base: d33c04ba3bb8062c935515c9a730beb50c74eb4b3d2a10a8f44580501ddf83ca430a69ed248eecf2c6910159aa3cc74735cfdbde0f844fe6949e676b64a9171b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
